apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-test-deployment
    labels:
        app: nginx-test
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx-test
    template:
        metadata:
            labels:
                app: nginx-test
        spec:
            containers:
                - name: nginx
                  image: nginx
                  ports:
                  - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-test-svc
spec:
    selector:
        app: nginx-test
    ports:
        - protocol: TCP
          port: 80
          
          
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-ingress
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress-class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: $1/
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  ingressClassName: nginx
  rules:
    - host: "nginx.staging.airomoni.com"
      http:
        paths:
          - path:
            pathType: Prefix
            backend:
              service:
                name: nginx-test-svc
                port:
                  number: 80
  tls:
    - hosts:
        - "nginx.staging.airomoni.com"
      secretName: airomoni-wildcard-tls
