apiVersion: v1
kind: Service
metadata:
  name: { { include "airopay-api.fullname" . } }
  labels: { { - include "airopay-api.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8084
      protocol: TCP
      name: https
  selector: { { - include "airopay-api.selectorLabels" . | nindent 4 } }
